# Generated by Django 3.2.2 on 2021-05-07 08:47

from django.db import migrations, models
import django.db.models.deletion
import mapbox_location_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aggiornamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('testo', models.TextField()),
                ('lat', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Latitude')),
                ('lng', models.DecimalField(decimal_places=8, max_digits=11, verbose_name='Longitude')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Segnalazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('redmine_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('token_validazione', models.CharField(db_index=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('email_tentativo', models.IntegerField(default=0)),
                ('email_validato', models.BooleanField(default=False)),
                ('email_inviato', models.BooleanField(default=False)),
                ('cellulare', models.CharField(max_length=15, verbose_name='Numero di cellulare')),
                ('location', mapbox_location_field.models.LocationField(map_attrs={'center': (10.515822538661212, 43.72580949521296), 'style': 'mapbox://styles/mightysharky/cjwgnjzr004bu1dnpw8kzxa72'})),
                ('address', mapbox_location_field.models.AddressAutoHiddenField(map_id='map')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('aggiornamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='segnala.aggiornamento')),
            ],
        ),
        migrations.AddField(
            model_name='aggiornamento',
            name='segnalazione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='segnala.segnalazione'),
        ),
    ]
