# Generated by Django 3.2.2 on 2021-05-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segnala', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='segnalazione',
            name='testo',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='segnalazione',
            name='titolo',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
