# Generated by Django 3.2.2 on 2021-05-07 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segnala', '0003_segnalazione_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='segnalazione',
            old_name='image',
            new_name='foto',
        ),
    ]
