# Generated by Django 3.2.3 on 2021-05-19 11:33

from django.db import migrations, models
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('segnala', '0004_rename_image_segnalazione_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='image',
            field=models.ImageField(upload_to='foto/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='segnalazione',
            name='location',
            field=mapbox_location_field.models.LocationField(map_attrs={'center': (10.515822538661212, 43.72580949521296), 'placeholder': 'Seleziona la posizione nella mappa.', 'style': 'mapbox://styles/mightysharky/cjwgnjzr004bu1dnpw8kzxa72'}, verbose_name='Posizione ed indirizzo'),
        ),
    ]
