# Generated by Django 3.2.3 on 2021-05-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segnala', '0005_auto_20210519_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='segnalazione',
            name='token_lettura',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
    ]
