# Generated by Django 3.2.3 on 2021-05-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segnala', '0006_segnalazione_token_lettura'),
    ]

    operations = [
        migrations.AddField(
            model_name='segnalazione',
            name='extra_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
