# Generated by Django 3.2.3 on 2021-05-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segnala', '0007_segnalazione_extra_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segnalazione',
            name='email_inviato',
        ),
        migrations.RemoveField(
            model_name='segnalazione',
            name='email_validato',
        ),
        migrations.AddField(
            model_name='segnalazione',
            name='stato',
            field=models.CharField(default='INIZIALE', max_length=50),
        ),
    ]
