# Generated by Django 3.2.3 on 2021-05-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segnala', '0009_auto_20210520_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='redmine_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
