# Generated by Django 3.2.3 on 2021-05-20 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('segnala', '0010_alter_categoria_redmine_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='segnalazione',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='segnala.categoria'),
            preserve_default=False,
        ),
    ]
