# Generated by Django 3.2.3 on 2021-05-22 16:22

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('segnala', '0012_alter_segnalazione_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segnalazione',
            name='address',
            field=mapbox_location_field.models.AddressAutoHiddenField(blank=True, map_id='map', null=True),
        ),
    ]
