# Generated by Django 3.2.3 on 2021-05-28 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('segnala', '0013_alter_segnalazione_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name_plural': 'Categorie'},
        ),
        migrations.AlterModelOptions(
            name='segnalazione',
            options={'verbose_name_plural': 'Segnalazioni'},
        ),
        migrations.AddField(
            model_name='categoria',
            name='ordine',
            field=models.SmallIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='segnalazione',
            name='categoria',
            field=models.ForeignKey(help_text='Seleziona la categoria e poi inserisci gli altri dati.', on_delete=django.db.models.deletion.CASCADE, to='segnala.categoria'),
        ),
    ]
