# Generated by Django 3.2.3 on 2021-05-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segnala', '0014_auto_20210528_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segnalazione',
            name='stato',
            field=models.CharField(choices=[('INIZIALE', 'INIZIALE'), ('EMAIL_FALLITO', 'EMAIL_FALLITO'), ('EMAIL_INVIATO', 'EMAIL_INVIATO'), ('EMAIL_VALIDATO', 'EMAIL_VALIDATO'), ('CREATO_IN_REDMINE', 'CREATO_IN_REDMINE')], default='INIZIALE', max_length=50),
        ),
    ]
