# Generated by Django 3.2.3 on 2021-05-31 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segnala', '0015_alter_segnalazione_stato'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['ordine'], 'verbose_name_plural': 'Categorie'},
        ),
        migrations.AddField(
            model_name='categoria',
            name='attiva',
            field=models.BooleanField(default=True, help_text='NON ANCORA USATO'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='testo_di_aiuto',
            field=models.CharField(blank=True, help_text='NON ANCORA USATO', max_length=300, null=True),
        ),
    ]
