# Generated by Django 3.2.3 on 2022-03-25 09:16

from django.db import migrations, models
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('segnala', '0017_auto_20210708_2150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notifica',
            options={'verbose_name_plural': 'Notifiche'},
        ),
        migrations.AddField(
            model_name='segnalazione',
            name='location_detail',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Dettagli sulla posizione'),
        ),
        migrations.AlterField(
            model_name='segnalazione',
            name='location',
            field=mapbox_location_field.models.LocationField(blank=True, map_attrs={'center': (10.515822538661212, 43.72580949521296), 'placeholder': 'Seleziona la posizione nella mappa.', 'style': 'mapbox://styles/mightysharky/cjwgnjzr004bu1dnpw8kzxa72'}, null=True, verbose_name='Indica sulla mappa la tua segnalazione. Oppure'),
        ),
    ]
